<?php

namespace Shoplo\AllegroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryAllegroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAllegroRepository extends EntityRepository
{
}
