<?php

namespace Shoplo\AllegroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SellAgainItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellAgainItemRepository extends EntityRepository
{
}
