imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: true
    session:         ~
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ShoploAllegroBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite:
            apply_to: "\.css$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    encryption: "%mailer_encryption%"

# OAuth
hwi_oauth:
    firewall_name: shoplo
    resource_owners:
        shoplo:
            type:                oauth1
            client_id:           %oauth_consumer_key%
            client_secret:       %oauth_consumer_secret%
            request_token_url:   http://api.shoplo.com/services/oauth/request_token
            access_token_url:    http://api.shoplo.com/services/oauth/access_token
            authorization_url:   http://api.shoplo.com/services/oauth/authorize
            infos_url:           http://api.shoplo.com/services/shop
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier:     shop.id
                nickname:       shop.name
                realname:       shop.shop_owner

# Allegro
shoplo_allegro:
    allegro:
        key: 0c7bc59c1
    shoplo:
        key: %oauth_consumer_key%
        secret: %oauth_consumer_secret%
