imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

framework:
    session:
        handler_id: session.handler.pdo

parameters:
    pdo.db_options:
        db_table:    "Session"
        db_id_col:   "session_id"
        db_data_col: "session_value"
        db_time_col: "session_time"

services:
    pdo:
        class: PDO
        arguments:
            - "mysql:dbname=%database_name%;host=%database_host%"
            - %database_user%
            - %database_password%

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, %pdo.db_options%]

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: sebastian@nexis.pl
            to_email:   [sebastian@nexis.pl,lech.grzegorz@gmail.com]
            subject:    "[Allegro] Internal Server Error"
            level:      debug

assetic:
    java: /usr/bin/java
    filters:
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
            apply_to: "\.js$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.css$"
