parameters:
    database_driver:        pdo_mysql
    database_host:          allegro.nexis.pl
    database_port:          ~
    database_name:          allegro_dev
    database_user:          allegro
    database_password:      fUeFXQKKNJ8LYaxmxZ5Fdo878cu9C85A

    mailer_transport:       smtp
    mailer_host:            localhost
    mailer_user:            ~
    mailer_password:        ~

    locale:                 pl
    secret:                 ThisTokenIsNotSoSecretChangeIt

    oauth_consumer_key:     GIPYVL7BQKgnttHGpb1XpJlgk9FQPIJX
    oauth_consumer_secret:  JubMSum8SpMXZ4qcpUseV6uiLuyQDNGo
