parameters:
    database_driver:        pdo_mysql
    database_host:          allegro.nexis.pl
    database_port:          ~
    database_name:          allegro_dev
    database_user:          allegro
    database_password:      fUeFXQKKNJ8LYaxmxZ5Fdo878cu9C85A

    mailer_transport:       smtp
    mailer_host:            localhost
    mailer_port:            ~
    mailer_user:            ~
    mailer_password:        ~
    mailer_encryption:      ~

    locale:                 pl
    secret:                 ThisTokenIsNotSoSecretChangeIt


    oauth_consumer_key:     WdAqtlmEf7sjaHziSOTnpqsFwUulRqtD
    oauth_consumer_secret:  K78U6toMZcyuuqY7oHVtD1a3xfeK1xzR
