jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oauth:
            id: shoplo.user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/zaloguj$
            anonymous: true

        hook:
            pattern: ^/hookme$
            anonymous: true

        shoplo:
            pattern:    ^/
            oauth:
                resource_owners:
                    shoplo: /zaloguj/shoplo
                login_path:         /zaloguj
                failure_path:       /zaloguj
                success_handler:    login_handler
                oauth_user_provider:
                    service:    shoplo.user_provider
            logout:
                path:   /wyloguj
                target: /
