shoplo_allegro_homepage:
    pattern:  /{action}/{page}
    defaults: { _controller: ShoploAllegroBundle:Homepage:index, action: trwajace, page: 1 }
    requirements:
        action: trwajace|zakonczone

shoplo_allegro_login:
    pattern:  /zaloguj
    defaults: { _controller: ShoploAllegroBundle:Homepage:login }

shoplo_allegro_logout:
    pattern:  /wyloguj

shoplo_allegro_show_item:
    pattern:  /pokaz/{itemId}
    defaults: { _controller: ShoploAllegroBundle:Homepage:show }
    requirements:
        itemId: \d+

shoplo_allegro_delete_item:
    pattern:  /usun/{itemId}
    defaults: { _controller: ShoploAllegroBundle:Homepage:delete }
    requirements:
        itemId: \d+

shoplo_allegro_finish_item:
    pattern:  /zakoncz/{itemId}
    defaults: { _controller: ShoploAllegroBundle:Homepage:finish }
    requirements:
        itemId: \d+

shoplo_allegro_finish_item_force:
    pattern:  /zakoncz/{itemId}/force
    defaults: { _controller: ShoploAllegroBundle:Homepage:finish, force: true }
    requirements:
        itemId: \d+

shoplo_allegro_profiles:
    pattern: /profile
    defaults: { _controller: ShoploAllegroBundle:Profile:index }

shoplo_allegro_edit_profile:
    pattern:  /profil/{profileId}/edytuj
    defaults: { _controller: ShoploAllegroBundle:Settings:auction }
    requirements:
        itemId: \d+

shoplo_allegro_delete_profile:
    pattern:  /profil/{profileId}/usun
    defaults: { _controller: ShoploAllegroBundle:Profile:delete }
    requirements:
        itemId: \d+

shoplo_allegro_settings:
    pattern: /ustawienia
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: shoplo_allegro_settings_login

shoplo_allegro_settings_login:
    pattern:  /ustawienia/logowanie
    defaults: { _controller: ShoploAllegroBundle:Settings:login }

shoplo_allegro_settings_location:
    pattern:  /ustawienia/lokalizacja
    defaults: { _controller: ShoploAllegroBundle:Settings:location }

shoplo_allegro_settings_auction:
    pattern:  /ustawienia/aukcja
    defaults: { _controller: ShoploAllegroBundle:Settings:auction }

shoplo_allegro_settings_payment:
    pattern:  /ustawienia/platnosc
    defaults: { _controller: ShoploAllegroBundle:Settings:payment }

shoplo_allegro_settings_delivery:
    pattern:  /ustawienia/dostawa
    defaults: { _controller: ShoploAllegroBundle:Settings:delivery }

shoplo_allegro_settings_mapping:
    pattern:  /ustawienia/kategorie
    defaults: { _controller: ShoploAllegroBundle:Settings:mapping }

shoplo_allegro_get_category_path:
    pattern:  /allegro/kategoria/{id}
    defaults: { _controller: ShoploAllegroBundle:Settings:getCategoryChildren }
    options:
        expose: true

shoplo_allegro_wizard:
    pattern:  /kreator
    defaults: { _controller: ShoploAllegroBundle:Wizard:index }

shoplo_allegro_webhook:
    pattern:  /hookme
    defaults: { _controller: ShoploAllegroBundle:Settings:webhook }
    requirements:
        _method:  POST
