shoplo_allegro_homepage:
    pattern:  /
    defaults: { _controller: ShoploAllegroBundle:Homepage:index }

shoplo_allegro_login:
    pattern:  /zaloguj
    defaults: { _controller: ShoploAllegroBundle:Homepage:login }

shoplo_allegro_logout:
    pattern:  /wyloguj

shoplo_allegro_settings:
    pattern: /ustawienia
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: shoplo_allegro_settings_login

shoplo_allegro_settings_login:
    pattern:  /ustawienia/logowanie
    defaults: { _controller: ShoploAllegroBundle:Settings:login }

shoplo_allegro_settings_location:
    pattern:  /ustawienia/lokalizacja
    defaults: { _controller: ShoploAllegroBundle:Settings:location }

shoplo_allegro_settings_auction:
    pattern:  /ustawienia/aukcja
    defaults: { _controller: ShoploAllegroBundle:Settings:auction }

shoplo_allegro_settings_payment:
    pattern:  /ustawienia/platnosc
    defaults: { _controller: ShoploAllegroBundle:Settings:payment }

shoplo_allegro_settings_delivery:
    pattern:  /ustawienia/dostawa
    defaults: { _controller: ShoploAllegroBundle:Settings:delivery }

shoplo_allegro_settings_profile:
    pattern:  /ustawienia/profil
    defaults: { _controller: ShoploAllegroBundle:Settings:profile }

shoplo_allegro_get_category_path:
    pattern:  /allegro/kategoria/{id}.json
    defaults: { _controller: ShoploAllegroBundle:Settings:getCategoryChildren }
    requirements:
        id: \d+
    options:
        expose: true

shoplo_allegro_wizard:
    pattern:  /kreator
    defaults: { _controller: ShoploAllegroBundle:Wizard:index }
