shoplo_allegro_homepage:
    pattern:  /
    defaults: { _controller: ShoploAllegroBundle:Homepage:index }

shoplo_allegro_login:
    pattern:  /logowanie
    defaults: { _controller: ShoploAllegroBundle:Homepage:login }

shoplo_allegro_settings:
    pattern:  /ustawienia
    defaults: { _controller: ShoploAllegroBundle:Settings:login }
