parameters:
    shoplo.webapi.class: Shoplo\AllegroBundle\WebAPI\Shoplo
    shoplo_allegro.webapi.class: Shoplo\AllegroBundle\WebAPI\Allegro
    shoplo_allegro.login_handler.class: Shoplo\AllegroBundle\Authentication\Handler\Login
    shoplo.user_provider.class: Shoplo\AllegroBundle\Security\Core\User\DoctrineUserProvider
    shoplo.twig_extension.class: Shoplo\AllegroBundle\Twig\BaseExtension

services:
    allegro:
        class: %shoplo_allegro.webapi.class%
        arguments: [%allegro.key%]
    shoplo:
        class: %shoplo.webapi.class%
        arguments: [%shoplo.key%, %shoplo.secret%, @security.context]
    login_handler:
        class: %shoplo_allegro.login_handler.class%
        arguments: [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    shoplo.user_provider:
        class: %shoplo.user_provider.class%
        arguments: [@doctrine]
    allegro.twig.base_extension:
        class: %shoplo.twig_extension.class%
        tags:
            - { name: twig.extension }
