parameters:
    shoplo.webapi.class: Shoplo\AllegroBundle\WebAPI\Shoplo
    shoplo_allegro.webapi.class: Shoplo\AllegroBundle\WebAPI\Allegro
    shoplo_allegro.login_handler.class: Shoplo\AllegroBundle\Authentication\Handler\Login

services:
    allegro:
        class: %shoplo_allegro.webapi.class%
        arguments: [%allegro.key%]
    shoplo:
        class: %shoplo.webapi.class%
        arguments: [%shoplo.key%, %shoplo.secret%, @security.context]
    login_handler:
        class: %shoplo_allegro.login_handler.class%
        arguments: [@router, @security.context, @doctrine]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
